### ISSUE TITLE
CORS configuration not working?

### ISSUE THREAD

**Issue by arran4** [trakt/api-help#348]
The cors configuration doesn't seem to be working as far as I can tell.
Here is the app:
https://arran4.github.io/trakt-import-github-action/ 
```
            let client = new jso.JSO({
.... // removed
                redirect_uri: "https://arran4.github.io/trakt-import-github-action/",
                token: 'https://api.trakt.tv/oauth/token',
                authorization: "https://api.trakt.tv/oauth/authorize",
                response_type: "code"
                //scopes: { request: ["authorization_code"]}
            })

            async function gettoken() {
                console.log("here")
                let token = await client.getToken()
                console.log("I got the token: ", token)
            }

            function logout() {
                client.wipeTokens()
            }

            client.callback().then(e => console.log("here2", e))
            console.log("here3", client);

```

And this is the error:
```
Access to fetch at 'https://api.trakt.tv/oauth/token' from origin 'https://arran4.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
VM221:1          POST https://api.trakt.tv/oauth/token net::ERR_FAILED 200
(anonymous) @ VM221:1
value @ jso.js:1
value @ jso.js:1
(anonymous) @ ?code=76c414f9d6e7eeeff1907325a2be2f72264774f613abc7bdbbd6108345caa013&state=88411544-eeef-4cc9-a45b-a6872be00016:29
VM221:1                  Uncaught (in promise) TypeError: Failed to fetch
    at <anonymous>:1:876
    at t.value (jso.js:1:40246)
    at t.value (jso.js:1:41442)
    at ?code=76c414f9d6e7eeeff1907325a2be2f72264774f613abc7bdbbd6108345caa013&state=88411544-eeef-4cc9-a45b-a6872be00016:29:20
```

Chrome version: `Version 101.0.4951.54 (Official Build) (64-bit)`

I am able to replicate the issue when I use the browser api mode in Apiary: https://trakt.docs.apiary.io/#introduction/terminology

Current CORS config on api app page:
![image](https://user-images.githubusercontent.com/111667/167970033-6446b699-ef1c-4940-99fd-7595f1677756.png)

**Comment by rectifyer** [comment]
Per the API docs, you should use the main Trakt website for the authorize link:
`https://trakt.tv/oauth/authorize`

I'm not sure that is causing the issue, but that is the first thing to check.

**Comment by rectifyer** [comment]
Did fixing the link get it working or is this still an issue?

**Comment by arran4** [comment]
Yeah I got it eventually. There were a couple issues. Including the one you pointed out.
